### ISSUE TITLE
Edit homepage HTML/CSS after demo-1

### ISSUE THREAD

**Issue by OfirMatasas** [redhat-beyond/Hotails#19]
Change the HTML/CSS of homepage.html for easier work on the project.
Guideline: create a simple HTML/CSS, with no external auto-generate program, and use bootstrap as needed.

**Comment by ErezCohenn** [comment]
@OfirMatasas  I think you can close this issue

**Comment by OfirMatasas** [comment]
> @OfirMatasas I think you can close this issue

The pull request about the "about" section closes it, as I converted the original homepage and made it the "about" of Hotails.

**Comment by ErezCohenn** [comment]
@OfirMatasas  I think you can close this issue
