### ISSUE TITLE
Create ERD diagram

### ISSUE THREAD

**Issue by OfirMatasas** [redhat-beyond/Hotails#20]
Define the database relations of the project

**Comment by Omeramsc** [comment]
Please refer to the [issue template](https://github.com/redhat-beyond/Hotails/blob/main/Contributing.md#issue-template) when writing an issue.

**Comment by ErezCohenn** [comment]
Adding a link for the online editor for the ERD diagram 
https://lucid.app/lucidspark/8969c0ba-5430-4e8c-90e1-28a23c2f3c7a/edit?invitationId=inv_63385825-f9f9-4cb2-bdac-9fb979645249#

**Comment by ErezCohenn** [comment]
> Please refer to the [issue template](https://github.com/redhat-beyond/Hotails/blob/main/Contributing.md#issue-template) when writing an issue.

@OfirMatasas I don't have the permission to change it, can you change it as omer mentioned or give the permission?
