### ISSUE TITLE
Add PyTest to workflows

### ISSUE THREAD

**Issue by OfirMatasas** [redhat-beyond/Hotails#29]
Just like Flake8, add PyTest to our repo checks, so any code we add to the project, following tests, will get tested before merging.

Must include:
- pytest.imi, including tests.py, test_*.py, *_tests.py type of files
- pytest.yml, for running PyTest
- A "truth" test, so show that PyTest works

**Comment by Omeramsc** [comment]
Please refer to the [issue template](https://github.com/redhat-beyond/Hotails/blob/main/Contributing.md#issue-template) when writing an issue.
