### ISSUE TITLE
Testing the communication between the users and the webserver 

### ISSUE THREAD

**Issue by ErezCohenn** [redhat-beyond/Hotails#53]
## Expected Behavior

Checking the communication between the users and the webserver 

## Current Behavior

There is no way to ensure that the users have communicated with the web

What is the current behavior?

## Acceptance Criteria

Having a test that tests the communication between the users and the webserver 

### Steps to Reproduce

1. create new folder tests for the project
2. build the test as described above
3. pass the test

**Comment by jeniaSakirko** [comment]
@ErezCohenn you can delete the `Prerequisites` part
