### ISSUE TITLE
Entrypoint test does not test what it needs too

### ISSUE THREAD

**Issue by Omeramsc** [redhat-beyond/Hotails#61]
## Expected Behavior

The test should check that something specific is actually showing up on the entry-point. 

## Current Behavior
#54 
The test calls the Django WSGI layers directly and attempts to test the HTTP connection with it, instead of checking the page view.

## Acceptance Criteria

The test should test the actual logic of the page (input\output\what is shown).

## Failure Information (for bugs)

The test does should test the actual logic of the page.

##BTW
It was I who merged this PR, sorry about the mess but I'll need you to fix it.

**Comment by ErezCohenn** [comment]
@Omeramsc i think you can close that issue
